### ISSUE TITLE
Websites seems to be down

### ISSUE THREAD

**Issue by sfeuga** [rubyversions/rubyversions.com#87]
Both website seems to be down:

- https://rubyversions.com/
- https://rubyversions.org/

**Comment by indirect** [comment]
DNS is fixed now, thanks for reporting!

**Comment by sfeuga** [comment]
You're welcome, but the `https://rubyversions.org/` website is still not working and serve a GitHub's 404.

**Comment by indirect** [comment]
Ohhh I used the wrong DNS record type 🤦 Fixed. Sorry about that!
